name: Build-Docker-Image
env:
  DOCKER_CR_LOGIN_SERVER: "nereuscrv2.azurecr.io"
  DOCKER_CR_USERNAME: "nereuscrv2"
  IMAGE_VERSION: ${{ github.sha }}
  IMAGE_NAME: "nereus-stablecoin-ui-dev"
  APP_NAME: "nf-stablecoin-ui"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: Login to Docker Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.DOCKER_CR_LOGIN_SERVER }}
          username: ${{ env.DOCKER_CR_USERNAME }}
          password: ${{ secrets.DOCKER_CR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_CR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest,${{ env.DOCKER_CR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'dev'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE_DEV }}
          images: '${{ env.DOCKER_CR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}'
